#!/usr/bin/env bash
# Installs nginx and configures it on a remote server

# Update package repositories
apt-get update

# Install nginx
apt-get install -y nginx

# Allow HTTP traffic for Nginx
ufw allow 'Nginx HTTP'

# Create a custom index page
echo 'Hello World!' > /var/www/html/index.html

# Start the nginx service
service nginx start

