#!/usr/bin/env bash
# install and configure HAproxy on lb-01 server and
# configure it to send traffic to web-01 and web-02 servers using roundrobin

sudo apt-get -y update

# install latest stable version
sudo apt-get -y install haproxy

# configure HAproxy
config=\
"
frontend azindotech-frontend
    bind *:80
	mode http
    default_backend azindotech-backend    
backend azindotech-backend
    balance roundrobin
    server 103560-web-01 35.175.105.33:80 check
    server 103560-web-02 52.86.214.98:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable start by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# restart haproxy
sudo service haproxy restart
